name: Checkout
on: [push]

jobs:
    checkout-actions:
      runs-on: ubuntu-latest
      steps:
        - name: list files Before
          run: ls -a
        - uses: actions/checkout@v4
        - name: list files After
          run: ls -a

    checkout-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: list files
              run: ls -a
            - name: checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: list files
              run: ls -a
                