name: Repo Events
on: [push, pull_request, issues]

jobs:
    checkout-tests:
      runs-on: ubuntu-latest
      steps:
        - name: checkout event test
          run: |
            echo $GITHUB_SHA
            echo $GITHUB_REF
        - uses: actions/checkout@v4