name: First Workflow
#on: [push]
on: [workflow_dispatch]
defaults:
  run:
    shell: bash

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Command
        run: |
          node -v
          npm -v
          
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers

  dependant-job:    
    runs-on: windows-latest
    needs: run-shell-commands
    defaults:
      run:
        shell: pwsh
    steps:
      - name: echo a string
        run: Write-Output "Windows String"
      #- name: Error Step
      #  run: doesnotexitsz
      
      - name: display_working_dir
        run: |
          #pwd
          Get-Locations
          dir
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

      - name: python shells
        shell: python
        run: |
          import platform
          print (plaform.processor())
