name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Learners!"
      - name: multiline command
        run: |
          node -v
          npm -v
