name: test1-docker
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        #runs-on: self-hosted
        container:
            image: nginx
            #credentials:
                #username: ${{secrets.DOCKER_USER}}
                #password: $DOCKER_PASS
            ports:
                - 80
            volumes:
                - test_vol:/usr/local/nginx/html
            env:
                T1: "Hello World"
        steps:            
            - name: test variable
              run: echo Hello
            - name: test variable
              run: |
                echo ${{secrets.DOCKER_USER}}
                echo ${{env.T1}}

    ubuntu-sleeper:
        runs-on: ubuntu-latest
        container: 
            image: amd64/busybox
            env:
                T1: Test
                USER: ${{secrets.DOCKER_USER}}
                PASS: ${{env.DOCKER_USER}}

            ports:
                - 80
        steps:
            - name: container in steps
              uses: docker://amd64/busybox:stable-uclibc
              with:
                entrypoint: echo
                args: echo hello

            - name: create sample files
              run: echo "Some Text" > test.txt
            
            - name: Show file content
              uses: docker://amd64/busybox:stable-uclibc
              with:
                entrypoint: cat
                args: test.txt
            
            - uses: actions/checkout@v3
            - name: execute scripts -- container in steps with scripts 
              uses: docker://amd64/busybox:stable-uclibc
              with:
                entrypoint: ./test-script.sh
                args: Hello World

            - name: environment test
              run: |
                echo $T1
                echo $USER
                echo $PASS
            
        
        