name: test1-docker
on: [push]

jobs:
    docker-job:
        #runs-on: ubuntu-latest
        runs-on: self-hosted
        container:
            image: nginx
            #credentials:
                #username: ${{secrets.DOCKER_USER}}
                #password: $DOCKER_PASS
            
            ports:
                - 80
            volumes:
                - test_vol:/usr/local/nginx/html
            env:
                T1: "Hello World"
        steps:            
            - name: test variable
              run: echo Hello
            - name: test variable
              run: |
                echo ${{secrets.DOCKER_USER}}
                echo ${{env.T1}}
